INSERT INTO nflteams (abbr, location, mascot) VALUES ('BUF', 'Buffalo', 'Bills');
INSERT INTO nflteams (abbr, location, mascot) VALUES ('MIA', 'Miami', 'Dolphins');
INSERT INTO nflteams (abbr, location, mascot) VALUES ('NE', 'New England', 'Patriots');
INSERT INTO nflteams (abbr, location, mascot) VALUES ('NYJ', 'New York', 'Jets');
INSERT INTO nflteams (abbr, location, mascot) VALUES ('CIN', 'Cincinnati', 'Bengals');
INSERT INTO nflteams (abbr, location, mascot) VALUES ('CLE', 'Cleveland', 'Browns');
INSERT INTO nflteams (abbr, location, mascot) VALUES ('PIT', 'Pittsburgh', 'Steelers');
INSERT INTO nflteams (abbr, location, mascot) VALUES ('BAL', 'Baltimore', 'Ravens');
INSERT INTO nflteams (abbr, location, mascot) VALUES ('TEN', 'Tennessee', 'Titans');
INSERT INTO nflteams (abbr, location, mascot) VALUES ('IND', 'Indianapolis', 'Colts');
INSERT INTO nflteams (abbr, location, mascot) VALUES ('JAX', 'Jacksonville', 'Jaguars');
INSERT INTO nflteams (abbr, location, mascot) VALUES ('HOU', 'Houston', 'Texans');
INSERT INTO nflteams (abbr, location, mascot) VALUES ('KC', 'Kansas City', 'Chiefs');
INSERT INTO nflteams (abbr, location, mascot) VALUES ('LV', 'Las Vegas', 'Raiders');
INSERT INTO nflteams (abbr, location, mascot) VALUES ('DEN', 'Denver', 'Broncos');
INSERT INTO nflteams (abbr, location, mascot) VALUES ('LAC', 'Los Angeles', 'Chargers');
INSERT INTO nflteams (abbr, location, mascot) VALUES ('PHI', 'Philadelphia', 'Eagles');
INSERT INTO nflteams (abbr, location, mascot) VALUES ('NYG', 'New York', 'Giants');
INSERT INTO nflteams (abbr, location, mascot) VALUES ('WAS', 'Washington', 'Commanders');
INSERT INTO nflteams (abbr, location, mascot) VALUES ('DAL', 'Dallas', 'Cowboys');
INSERT INTO nflteams (abbr, location, mascot) VALUES ('MIN', 'Minnesota', 'Vikings');
INSERT INTO nflteams (abbr, location, mascot) VALUES ('CHI', 'Chicago', 'Bears');
INSERT INTO nflteams (abbr, location, mascot) VALUES ('DET', 'Detroit', 'Lions');
INSERT INTO nflteams (abbr, location, mascot) VALUES ('GB', 'Green Bay', 'Packers');
INSERT INTO nflteams (abbr, location, mascot) VALUES ('NO', 'New Orleans', 'Saints');
INSERT INTO nflteams (abbr, location, mascot) VALUES ('TB', 'Tampa Bay', 'Buccaneers');
INSERT INTO nflteams (abbr, location, mascot) VALUES ('CAR', 'Carolina', 'Panthers');
INSERT INTO nflteams (abbr, location, mascot) VALUES ('ATL', 'Atlanta', 'Falcons');
INSERT INTO nflteams (abbr, location, mascot) VALUES ('SEA', 'Seattle', 'Seahawks');
INSERT INTO nflteams (abbr, location, mascot) VALUES ('LA', 'Los Angeles', 'Rams');
INSERT INTO nflteams (abbr, location, mascot) VALUES ('SF', 'San Francisco', '49ers');
INSERT INTO nflteams (abbr, location, mascot) VALUES ('ARI', 'Arizona', 'Cardinals');

INSERT INTO globals (currentweek, urlpath) VALUES (1, 'localhost/ffnh/');
INSERT INTO profiles (username, password) VALUES ('ADMIN', 'ADMIN');
INSERT INTO profiles (username, password) VALUES ('TRANSACTION', 'TRANSACTION');